// <auto-generated />
using System;
using AOGSystem.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AOGSystem.Persistence.Migrations
{
    [DbContext(typeof(AOGSystemContext))]
    partial class AOGSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AOGSystem.Domain.FollowUp.HomeBaseFollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AirCraft")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("air_craft");

                    b.Property<DateTime>("CreatedAT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("customer");

                    b.Property<string>("ESD")
                        .HasColumnType("longtext")
                        .HasColumnName("esd");

                    b.Property<bool>("NeedHigherMgntAttn")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("need_higher_mgnt_attn");

                    b.Property<string>("OrderType")
                        .HasColumnType("longtext")
                        .HasColumnName("order_type");

                    b.Property<string>("PONumber")
                        .HasColumnType("longtext")
                        .HasColumnName("po_number");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rid");

                    b.Property<int>("RemarkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("request_date");

                    b.Property<string>("TailNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tail_no");

                    b.Property<string>("UOM")
                        .HasColumnType("longtext")
                        .HasColumnName("uom");

                    b.Property<DateTime>("UpdatedAT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.Property<string>("Vendor")
                        .HasColumnType("longtext")
                        .HasColumnName("vendor");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.ToTable("home_base_follow_ups", "AOGsystem");
                });

            modelBuilder.Entity("AOGSystem.Domain.FollowUp.Remark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<int?>("HomeBaseFollowUpId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<int>("RemarkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("HomeBaseFollowUpId");

                    b.HasIndex("RemarkId");

                    b.ToTable("remarks", "AOGsystem");
                });

            modelBuilder.Entity("AOGSystem.Domain.General.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("BillToAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("bill_to_address");

                    b.Property<string>("City")
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PaymentTerm")
                        .HasColumnType("longtext")
                        .HasColumnName("payment_term");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("ShipToAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("ship_to_address");

                    b.Property<DateTime>("UpdatedAT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("companies", "AOGsystem");
                });

            modelBuilder.Entity("AOGSystem.Domain.General.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("FinancialClass")
                        .HasColumnType("longtext")
                        .HasColumnName("financial_class");

                    b.Property<int?>("HomeBaseFollowUpId")
                        .HasColumnType("int");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("part_number");

                    b.Property<int?>("QuotationPartListId")
                        .HasColumnType("int");

                    b.Property<string>("StockNo")
                        .HasColumnType("longtext")
                        .HasColumnName("stock_no");

                    b.Property<DateTime>("UpdatedAT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("HomeBaseFollowUpId");

                    b.HasIndex("QuotationPartListId");

                    b.ToTable("parts", "AOGsystem");
                });

            modelBuilder.Entity("AOGSystem.Domain.Quotation.Quotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<bool>("Exchange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("exchange");

                    b.Property<bool>("Loan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("loan");

                    b.Property<string>("RequestedByEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("requested_by_email");

                    b.Property<string>("RequestedByName")
                        .HasColumnType("longtext")
                        .HasColumnName("requested_by_name");

                    b.Property<string>("RequestedByPhone")
                        .HasColumnType("longtext")
                        .HasColumnName("requested_by_phone");

                    b.Property<bool>("Sales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("sales");

                    b.Property<DateTime>("UpdatedAT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("quotations", "AOGsystem");
                });

            modelBuilder.Entity("AOGSystem.Domain.Quotation.QuotationPartList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Condition")
                        .HasColumnType("longtext")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("current_price");

                    b.Property<decimal>("ExchangePrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("exchange_price");

                    b.Property<decimal>("LoanPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("loan_price");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("QuotationId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalesPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("sales_price");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("StockLocation")
                        .HasColumnType("longtext")
                        .HasColumnName("stock_location");

                    b.Property<DateTime>("UpdatedAT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("QuotationId");

                    b.ToTable("quotation_partLists", "AOGsystem");
                });

            modelBuilder.Entity("AOGSystem.Domain.FollowUp.HomeBaseFollowUp", b =>
                {
                    b.HasOne("AOGSystem.Domain.General.Part", null)
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("part_id");
                });

            modelBuilder.Entity("AOGSystem.Domain.FollowUp.Remark", b =>
                {
                    b.HasOne("AOGSystem.Domain.FollowUp.HomeBaseFollowUp", null)
                        .WithMany("Remarks")
                        .HasForeignKey("HomeBaseFollowUpId");

                    b.HasOne("AOGSystem.Domain.FollowUp.HomeBaseFollowUp", null)
                        .WithMany()
                        .HasForeignKey("RemarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AOGSystem.Domain.General.Company", b =>
                {
                    b.HasOne("AOGSystem.Domain.Quotation.Quotation", null)
                        .WithOne("Company")
                        .HasForeignKey("AOGSystem.Domain.General.Company", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AOGSystem.Domain.General.Part", b =>
                {
                    b.HasOne("AOGSystem.Domain.FollowUp.HomeBaseFollowUp", null)
                        .WithMany("Part")
                        .HasForeignKey("HomeBaseFollowUpId");

                    b.HasOne("AOGSystem.Domain.Quotation.QuotationPartList", null)
                        .WithMany("Parts")
                        .HasForeignKey("QuotationPartListId");
                });

            modelBuilder.Entity("AOGSystem.Domain.Quotation.QuotationPartList", b =>
                {
                    b.HasOne("AOGSystem.Domain.General.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AOGSystem.Domain.Quotation.Quotation", null)
                        .WithMany("QuotationPartsLists")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("AOGSystem.Domain.FollowUp.HomeBaseFollowUp", b =>
                {
                    b.Navigation("Part");

                    b.Navigation("Remarks");
                });

            modelBuilder.Entity("AOGSystem.Domain.Quotation.Quotation", b =>
                {
                    b.Navigation("Company");

                    b.Navigation("QuotationPartsLists");
                });

            modelBuilder.Entity("AOGSystem.Domain.Quotation.QuotationPartList", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
